version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ucn_admin
      POSTGRES_PASSWORD: Passw0rd_seguro2025
      POSTGRES_DB: estacionamiento_ucn
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    env_file: ./backend/database/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
